
version: 0.2

env:
  variables:
    AWS_REGION: us-west-2
    ACCOUNT_ID: "962804699607"
    REPO_NAME: "aws-innovators-repo"
    IMAGE_NAME: "aws-innovators-image"
  # If you want to tag with the Git commit automatically:
  # compute_type 'CODEBUILD_RESOLVED_SOURCE_VERSION' is provided by CodeBuild
  # If you prefer only :latest, you can remove the additional tag lines below.

phases:
  install:
    commands:
      - echo "Install phase..."
      - aws --version
      - docker --version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR in $AWS_REGION..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # Ensure the repository exists (no-op if it already exists)
      - |
        aws ecr describe-repositories --repository-names $REPO_NAME --region $AWS_REGION >/dev/null 2>&1 \
        || aws ecr create-repository --repository-name $REPO_NAME --image-scanning-configuration scanOnPush=true --region $AWS_REGION
      - echo "Repository $REPO_NAME is ready."

  build:
    commands:
      - echo "Building Docker image on $(date)"
      - cd src
      - docker build -t $IMAGE_NAME:latest .
      # Add an immutable tag (optional but recommended)
      - IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME
      - docker tag $IMAGE_NAME:latest $IMAGE_URI:latest
      - if [ -n "${CODEBUILD_RESOLVED_SOURCE_VERSION}" ]; then docker tag $IMAGE_NAME:latest $IMAGE_URI:${CODEBUILD_RESOLVED_SOURCE_VERSION}; fi

  post_build:
    commands:
      - echo "Build complete on $(date). Pushing image(s) to ECR..."
      - docker push $IMAGE_URI:latest
      - if [ -n "${CODEBUILD_RESOLVED_SOURCE_VERSION}" ]; then docker push $IMAGE_URI:${CODEBUILD_RESOLVED_SOURCE_VERSION}; fi
      - echo "ECR push finished."
