
version: 0.2

env:
  variables:
    AWS_REGION: us-west-2
    ACCOUNT_ID: "962804699607"
    REPO_NAME: "aws-innovators-repo"
    IMAGE_NAME: "aws-innovators-image"
    IMAGE_URI: "962804699607.dkr.ecr.us-west-2.amazonaws.com/aws-innovators-repo"

phases:
  install:
    commands:
      - set -euo pipefail
      - aws --version
      - docker --version

  pre_build:
    commands:
      - aws sts get-caller-identity
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - |
        aws ecr describe-repositories --repository-names "$REPO_NAME" --region "$AWS_REGION" >/dev/null 2>&1 \
        || aws ecr create-repository --repository-name "$REPO_NAME" --image-scanning-configuration scanOnPush=true --region "$AWS_REGION"

  build:
    commands:
      - echo "Working dir: $CODEBUILD_SRC_DIR"
      - ls -la
      - echo "Building Docker image on $(date)"
      - docker build -t $IMAGE_NAME:latest .
      - docker tag $IMAGE_NAME:latest $IMAGE_URI:latest

  post_build:
    commands:
      - docker images --format '{{.Repository}}:{{.Tag}}' | grep -E "^$IMAGE_URI:latest$" || (echo "Tag missing" && exit 1)
      - docker push $IMAGE_URI:latest
